package com.codegym.auto_marketing_server.dto;

import com.codegym.auto_marketing_server.enums.PostStatus;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Schema(description = "Enhanced post response with complete content details")
public class PostResponseDTO {

    @Schema(description = "Post ID", example = "48")
    private Long id;

    @Schema(description = "Associated topic ID", example = "35")
    private Long topicId;

    // ========== CONTENT FIELDS ==========
    @Schema(description = "Post title", example = "🚀 AI Thay Đổi Cách Làm Việc - Bạn Đã Sẵn Sàng?")
    private String title;

    @Schema(description = "Complete post content in Vietnamese", example = "Trí tuệ nhân tạo không còn là tương lai xa vời...")
    private String content;

    @Schema(description = "Hashtags for the post", example = "#AI #ChuyenDoiSo #DoanhNghiepVietNam")
    private String hashtag;

    // ========== GENERATION METADATA ==========
    @Schema(description = "Whether content was generated by AI", example = "true")
    private Boolean generatedByAI = true;

    @Schema(description = "AI prompt used for generation")
    private String aiPrompt;

    @Schema(description = "AI model used for generation", example = "gpt-4")
    private String aiModel;

    @Schema(description = "Content type used", example = "social_post")
    private String contentType;

    @Schema(description = "Content tone used", example = "professional")
    private String tone;

    @Schema(description = "Target audience", example = "1")
    private Integer targetAudience;

    @Schema(description = "Token usage information")
    private String tokenUsage;

    @Schema(description = "AI generation timestamp")
    private LocalDateTime generateTime;

    // ========== STATUS & SCHEDULING ==========
    @Schema(description = "Current post status")
    private PostStatus status = PostStatus.PUBLISHED;

    // ========== AUDIT FIELDS ==========
    @Schema(description = "Content creation date")
    private LocalDate createdAt;

    @Schema(description = "Last update date")
    private LocalDate updatedAt;

    // ========== RELATIONSHIPS ==========
    @Schema(description = "Associated topic information")
    private TopicResponseDTO topic;

    private String imageUrl;

    // Thêm trường này để trả về danh sách nhiều ảnh
    private List<String> imageUrls;
}
